id: IF790A4DF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T16:37:59+00:00'
last_modified: '2022-06-08T09:07:59.969682+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8226
  title: བཻ་ཌཱུརྱ་གཡའ་སེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E6EB:
      image_group_id: I5875
      title: ''
      total_pages: 548
      order: 1
      base_file: E6EB.txt
    4E54:
      image_group_id: I5876
      title: ''
      total_pages: 550
      order: 2
      base_file: 4E54.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
