id: IF790A4DF
legacy_id: P009172
ocr_import_info:
  bdrc_scan_id: W8226
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T16:34:19'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:18:01.377223+00:00'
last_modified: 2022-09-04 11:18:42.760951
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8226
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW8226
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཻ་ཌཱུརྱ་གཡའ་སེལ།
  author: སྡེ་སྲིད་སངས་རྒྱས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.7161872908408293
  ocr_word_median_confidence_index: 0.7799999713897705
quality: null
bases:
  I5876:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5876
      total_pages: 550
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I5876.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.725606229871355
    legacy_id: v002
  I5875:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5875
      total_pages: 548
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5875.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.706831054064796
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
